//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonRS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonRS.Resources.ValidationMes", typeof(ValidationMes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa môn học thành công.
        /// </summary>
        public static string mes_ChinhSuaMonHocThanhCong {
            get {
                return ResourceManager.GetString("mes_ChinhSuaMonHocThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa môn học thất bại, xin vui lòng kiểm tra lại !.
        /// </summary>
        public static string mes_ChinhSuaMonHocThatBai {
            get {
                return ResourceManager.GetString("mes_ChinhSuaMonHocThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa lưu ma trận liên kết  ! Vui lòng thử lại..
        /// </summary>
        public static string mes_ChuaLuuMatran {
            get {
                return ResourceManager.GetString("mes_ChuaLuuMatran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xóa kết quả học tập mong đợi ?.
        /// </summary>
        public static string mes_ConfirmCDRCTDT {
            get {
                return ResourceManager.GetString("mes_ConfirmCDRCTDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xóa mục tiêu đào tạo cụ thể ?.
        /// </summary>
        public static string mes_ConfirmMTCTDT {
            get {
                return ResourceManager.GetString("mes_ConfirmMTCTDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xóa học phần này?.
        /// </summary>
        public static string mes_ConfirmXoaHP {
            get {
                return ResourceManager.GetString("mes_ConfirmXoaHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu ma trận trống ! Vui lòng thêm dữ liệu..
        /// </summary>
        public static string mes_DuLieuMaTranTrong {
            get {
                return ResourceManager.GetString("mes_DuLieuMaTranTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn hệ đào tạo.
        /// </summary>
        public static string mes_HeDT {
            get {
                return ResourceManager.GetString("mes_HeDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập học kỳ.
        /// </summary>
        public static string mes_HocKy {
            get {
                return ResourceManager.GetString("mes_HocKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn khối kiến thức.
        /// </summary>
        public static string mes_KhoiKienThuc {
            get {
                return ResourceManager.GetString("mes_KhoiKienThuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn loại kiến thức.
        /// </summary>
        public static string mes_LoaiKienThuc {
            get {
                return ResourceManager.GetString("mes_LoaiKienThuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu ma trận liên kết thành công.
        /// </summary>
        public static string mes_LuuMaTranBuoc2 {
            get {
                return ResourceManager.GetString("mes_LuuMaTranBuoc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu ma trận liên kết thành công.
        /// </summary>
        public static string mes_LuuMaTranBuoc3 {
            get {
                return ResourceManager.GetString("mes_LuuMaTranBuoc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu ma trận trước khi tiếp tục.
        /// </summary>
        public static string mes_LuuMaTranTruocKhiTiepTuc {
            get {
                return ResourceManager.GetString("mes_LuuMaTranTruocKhiTiepTuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã học phần.
        /// </summary>
        public static string mes_MaHT {
            get {
                return ResourceManager.GetString("mes_MaHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn ngành đào tạo.
        /// </summary>
        public static string mes_NganhDT {
            get {
                return ResourceManager.GetString("mes_NganhDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập phiên bản chương trình Đào tạo.
        /// </summary>
        public static string mes_PhienBan {
            get {
                return ResourceManager.GetString("mes_PhienBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa chuẩn đầu ra chương trình đào tạo không thành công, xin vui lòng kiểm tra lại !.
        /// </summary>
        public static string mes_SuaKhongThanhCongCDRCTDT {
            get {
                return ResourceManager.GetString("mes_SuaKhongThanhCongCDRCTDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa mục tiêu đào tạo cụ thể không thành công, xin vui lòng kiểm tra lại !.
        /// </summary>
        public static string mes_SuaKhongThanhCongMucTieu {
            get {
                return ResourceManager.GetString("mes_SuaKhongThanhCongMucTieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa thành công chuẩn đầu ra chương trình đào tạo.
        /// </summary>
        public static string mes_SuaThanhCongCDRCTDT {
            get {
                return ResourceManager.GetString("mes_SuaThanhCongCDRCTDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa thành công mục tiêu đào tạo cụ thể.
        /// </summary>
        public static string mes_SuaThanhCongMucTieu {
            get {
                return ResourceManager.GetString("mes_SuaThanhCongMucTieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên chương trình đào tạo.
        /// </summary>
        public static string mes_TenCTDT {
            get {
                return ResourceManager.GetString("mes_TenCTDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên học phần.
        /// </summary>
        public static string mes_TenHP {
            get {
                return ResourceManager.GetString("mes_TenHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm không thành công chuẩn đầu ra chương trình đào tạo, xin vui lòng kiểm tra lại !.
        /// </summary>
        public static string mes_ThemKhongThanhCongCDRCTDT {
            get {
                return ResourceManager.GetString("mes_ThemKhongThanhCongCDRCTDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm không thành công mục tiêu đào tạo cụ thể, xin vui lòng kiểm tra lại !.
        /// </summary>
        public static string mes_ThemKhongThanhCongMucTieu {
            get {
                return ResourceManager.GetString("mes_ThemKhongThanhCongMucTieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm môn học thất bại, xin vui lòng kiểm tra lại.
        /// </summary>
        public static string mes_ThemMongHocKhongThanhCong {
            get {
                return ResourceManager.GetString("mes_ThemMongHocKhongThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thành công môn học .
        /// </summary>
        public static string mes_ThemMonHocThanhCong {
            get {
                return ResourceManager.GetString("mes_ThemMonHocThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thành công chuẩn đầu ra chương trình đào tạo.
        /// </summary>
        public static string mes_ThemThanhCongCDRCTDT {
            get {
                return ResourceManager.GetString("mes_ThemThanhCongCDRCTDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thành công mục tiêu đào tạo cụ thể.
        /// </summary>
        public static string mes_ThemThanhCongMucTieu {
            get {
                return ResourceManager.GetString("mes_ThemThanhCongMucTieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa chuẩn đầu ra chương trình đào tạo không thành công, xin vui lòng kiểm tra lại !.
        /// </summary>
        public static string mes_XoaKhongThanhCongCDRCTDT {
            get {
                return ResourceManager.GetString("mes_XoaKhongThanhCongCDRCTDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả học tập mong đợi đang được liên kết, xin vui lòng kiểm tra lại !.
        /// </summary>
        public static string mes_XoaLienKetCDR {
            get {
                return ResourceManager.GetString("mes_XoaLienKetCDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Môn học đang được liên kết, xin vui lòng kiểm tra lại !.
        /// </summary>
        public static string mes_XoaLienKetMonHoc {
            get {
                return ResourceManager.GetString("mes_XoaLienKetMonHoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mục tiêu đào tạo cụ thể đang được liên kết, xin vui lòng kiểm tra lại !.
        /// </summary>
        public static string mes_XoaLienKetMucTieu {
            get {
                return ResourceManager.GetString("mes_XoaLienKetMucTieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa môn học thành công.
        /// </summary>
        public static string mes_XoaMonHocThanhCong {
            get {
                return ResourceManager.GetString("mes_XoaMonHocThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa môn học thất bại .
        /// </summary>
        public static string mes_XoaMonHocThatBai {
            get {
                return ResourceManager.GetString("mes_XoaMonHocThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa không thành công mục tiêu đào tạo cụ thể.
        /// </summary>
        public static string mes_XoaMucTieuKhongThanhCong {
            get {
                return ResourceManager.GetString("mes_XoaMucTieuKhongThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công mục tiêu đào tạo cụ thể.
        /// </summary>
        public static string mes_XoaMucTieuThanhCong {
            get {
                return ResourceManager.GetString("mes_XoaMucTieuThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công chuẩn đầu ra chương trình đào tạo.
        /// </summary>
        public static string mes_XoaThanhCongCDRCTDT {
            get {
                return ResourceManager.GetString("mes_XoaThanhCongCDRCTDT", resourceCulture);
            }
        }
    }
}
