//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonRS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Variables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Variables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonRS.Resources.Variables", typeof(Variables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string TrangthaiDC_ChoPheDuyet {
            get {
                return ResourceManager.GetString("TrangthaiDC_ChoPheDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string TrangthaiDC_ChuaCapNhat {
            get {
                return ResourceManager.GetString("TrangthaiDC_ChuaCapNhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string TrangthaiDC_DaPheDuyet {
            get {
                return ResourceManager.GetString("TrangthaiDC_DaPheDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string TrangthaiDC_LuuNhap {
            get {
                return ResourceManager.GetString("TrangthaiDC_LuuNhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string TrangthaiDC_TuChoi {
            get {
                return ResourceManager.GetString("TrangthaiDC_TuChoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string TrangthaiDCGV_DongY {
            get {
                return ResourceManager.GetString("TrangthaiDCGV_DongY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string TrangthaiDCGV_DuocGuiMail {
            get {
                return ResourceManager.GetString("TrangthaiDCGV_DuocGuiMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string TrangthaiDCGV_DuocPC {
            get {
                return ResourceManager.GetString("TrangthaiDCGV_DuocPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string TrangthaiDCGV_TuChoi {
            get {
                return ResourceManager.GetString("TrangthaiDCGV_TuChoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string TrangthaiKH_CapNhatDCHP {
            get {
                return ResourceManager.GetString("TrangthaiKH_CapNhatDCHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string TrangthaiKH_CapNhatTrienKhaiHP {
            get {
                return ResourceManager.GetString("TrangthaiKH_CapNhatTrienKhaiHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string TrangthaiKH_KhoiTao {
            get {
                return ResourceManager.GetString("TrangthaiKH_KhoiTao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string TrangthaiKH_LuuTru {
            get {
                return ResourceManager.GetString("TrangthaiKH_LuuTru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string TrangthaiKH_ThucThi {
            get {
                return ResourceManager.GetString("TrangthaiKH_ThucThi", resourceCulture);
            }
        }
    }
}
