//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonRS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommonRS.Resources.VI", typeof(VI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45 Nguyễn Khắc Nhu, Phường Cô Giang, Quận 1, Tp. HCM.
        /// </summary>
        public static string info_SchoolAddress {
            get {
                return ResourceManager.GetString("info_SchoolAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được để trống công cụ đánh giá và thời điểm đánh giá.
        /// </summary>
        public static string mes_CCDGTrong {
            get {
                return ResourceManager.GetString("mes_CCDGTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn một Ngành học.
        /// </summary>
        public static string mes_ChonNganhHoc {
            get {
                return ResourceManager.GetString("mes_ChonNganhHoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn Ngành học khác.
        /// </summary>
        public static string mes_ChonNganhHocKhac {
            get {
                return ResourceManager.GetString("mes_ChonNganhHocKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn toàn bộ thư mời giảng dạy.
        /// </summary>
        public static string mes_ChonToanBoThuMoiGD {
            get {
                return ResourceManager.GetString("mes_ChonToanBoThuMoiGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn Khóa học muốn tạo kế hoạch giảng dạy.
        /// </summary>
        public static string mes_ChuaChonKH {
            get {
                return ResourceManager.GetString("mes_ChuaChonKH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn thành phần đánh giá.
        /// </summary>
        public static string mes_ChuaChonTPDG {
            get {
                return ResourceManager.GetString("mes_ChuaChonTPDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Học kỳ chưa được phân công giảng dạy.
        /// </summary>
        public static string mes_ChuaDuocPC {
            get {
                return ResourceManager.GetString("mes_ChuaDuocPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã gửi email đến Giảng viên.
        /// </summary>
        public static string mes_DaGuiMail {
            get {
                return ResourceManager.GetString("mes_DaGuiMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã nộp đề cương học phần {tenhp} thành công.
        /// </summary>
        public static string mes_DaNopDCThanhCong {
            get {
                return ResourceManager.GetString("mes_DaNopDCThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thiết lập vai trò cho tài khoản.
        /// </summary>
        public static string mes_DaThietLapRole {
            get {
                return ResourceManager.GetString("mes_DaThietLapRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng lựa chọn ngày bắt đầu và kết thúc học kỳ.
        /// </summary>
        public static string mes_DienNgayBDKT {
            get {
                return ResourceManager.GetString("mes_DienNgayBDKT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã đồng ý phê duyệt đề cương học phần.
        /// </summary>
        public static string mes_DongYPheDuyet {
            get {
                return ResourceManager.GetString("mes_DongYPheDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn không đúng định dạng.
        /// </summary>
        public static string mes_DuongDanKhongDung {
            get {
                return ResourceManager.GetString("mes_DuongDanKhongDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạn cập nhật đề cương bị bỏ trống.
        /// </summary>
        public static string mes_HanCNDCTrong {
            get {
                return ResourceManager.GetString("mes_HanCNDCTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạn cập nhật đề cương bị bỏ trống.
        /// </summary>
        public static string mes_HanNopDCTrong {
            get {
                return ResourceManager.GetString("mes_HanNopDCTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế hoạch giảng dạy đã được tạo.
        /// </summary>
        public static string mes_KHDTDaCo {
            get {
                return ResourceManager.GetString("mes_KHDTDaCo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có gì thay đổi để lưu.
        /// </summary>
        public static string mes_KhongCoGiThayDoi {
            get {
                return ResourceManager.GetString("mes_KhongCoGiThayDoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có giáo viên nào để gửi mail.
        /// </summary>
        public static string mes_KhongCoGV {
            get {
                return ResourceManager.GetString("mes_KhongCoGV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có giảng viên để gửi mail.
        /// </summary>
        public static string mes_KhongCoGVGuiMail {
            get {
                return ResourceManager.GetString("mes_KhongCoGVGuiMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm học chưa có học kỳ.
        /// </summary>
        public static string mes_KhongCoHK {
            get {
                return ResourceManager.GetString("mes_KhongCoHK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các trường thông tin không được để trống.
        /// </summary>
        public static string mes_KhongDuocDeTrong {
            get {
                return ResourceManager.GetString("mes_KhongDuocDeTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể gửi mail.
        /// </summary>
        public static string mes_KhongGuiMail {
            get {
                return ResourceManager.GetString("mes_KhongGuiMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không lưu được dữ liệu.
        /// </summary>
        public static string mes_KhongLuuDuoc {
            get {
                return ResourceManager.GetString("mes_KhongLuuDuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy nhập đủ thông tin nội dung.
        /// </summary>
        public static string mes_KhongNhapDayDu {
            get {
                return ResourceManager.GetString("mes_KhongNhapDayDu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tải được dữ liệu.
        /// </summary>
        public static string mes_KhongTaiDuoc {
            get {
                return ResourceManager.GetString("mes_KhongTaiDuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể phê duyệt đề cương.
        /// </summary>
        public static string mes_KhongThePheDuyetDC {
            get {
                return ResourceManager.GetString("mes_KhongThePheDuyetDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể tạo.
        /// </summary>
        public static string mes_KhongTheTao {
            get {
                return ResourceManager.GetString("mes_KhongTheTao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thê tạo thêm thẻ mới được nữa.
        /// </summary>
        public static string mes_KhongTheThemMoiDuocNua {
            get {
                return ResourceManager.GetString("mes_KhongTheThemMoiDuocNua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu.
        /// </summary>
        public static string mes_KhongTimThay {
            get {
                return ResourceManager.GetString("mes_KhongTimThay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy chọn Đồng ý hoặc Từ chối trước khi nhấn nút Xác nhận.
        /// </summary>
        public static string mes_LuaChonTruocKhiPheDuyetDC {
            get {
                return ResourceManager.GetString("mes_LuaChonTruocKhiPheDuyetDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã lưu dữ liệu vào bảng.
        /// </summary>
        public static string mes_LuuBang {
            get {
                return ResourceManager.GetString("mes_LuuBang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã lưu gom nhóm tiêu chí.
        /// </summary>
        public static string mes_LuuGomNhomTC {
            get {
                return ResourceManager.GetString("mes_LuuGomNhomTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu dữ liệu thành công.
        /// </summary>
        public static string mes_LuuThanhCong {
            get {
                return ResourceManager.GetString("mes_LuuThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần lưu trước khi chuyển trang.
        /// </summary>
        public static string mes_LuuTruocKhiChuyen {
            get {
                return ResourceManager.GetString("mes_LuuTruocKhiChuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Môn học đã được chọn, vui lòng lựa chọn môn học khác.
        /// </summary>
        public static string mes_MonHocDaDuocChon {
            get {
                return ResourceManager.GetString("mes_MonHocDaDuocChon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mục tiêu học phần không được để trống.
        /// </summary>
        public static string mes_MucTieuTrong {
            get {
                return ResourceManager.GetString("mes_MucTieuTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm học chưa có dữ liệu.
        /// </summary>
        public static string mes_NamHocChuaCoDL {
            get {
                return ResourceManager.GetString("mes_NamHocChuaCoDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm học phải có giá trị tăng dần và cách nhau 1 năm.
        /// </summary>
        public static string mes_NamHocTangDan {
            get {
                return ResourceManager.GetString("mes_NamHocTangDan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm Học bị trống.
        /// </summary>
        public static string mes_NamHocTrong {
            get {
                return ResourceManager.GetString("mes_NamHocTrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian bắt đầu và kết thúc học kỳ không trùng khớp với năm học.
        /// </summary>
        public static string mes_NgayBDNgayKTTrungVoiNam {
            get {
                return ResourceManager.GetString("mes_NgayBDNgayKTTrungVoiNam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kết thúc học kỳ phải lớn hơn ngày bắt đầu học kỳ. Vui lòng chọn lại.
        /// </summary>
        public static string mes_NgayKTLonHonBD {
            get {
                return ResourceManager.GetString("mes_NgayKTLonHonBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập lý do khi từ chối.
        /// </summary>
        public static string mes_NhapLyDoTuChoi {
            get {
                return ResourceManager.GetString("mes_NhapLyDoTuChoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đề cương đã được phê duyệt.
        /// </summary>
        public static string mes_PheDuyetDCThanhCong {
            get {
                return ResourceManager.GetString("mes_PheDuyetDCThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã lưu chỉnh sửa công cụ và thời điểm đánh giá.
        /// </summary>
        public static string mes_SuaCCDG {
            get {
                return ResourceManager.GetString("mes_SuaCCDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã lưu kết quả học tập mong đợi vừa được chỉnh sửa.
        /// </summary>
        public static string mes_SuaKQHT {
            get {
                return ResourceManager.GetString("mes_SuaKQHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã lưu chỉnh sửa thành phần đánh giá vào bảng.
        /// </summary>
        public static string mes_SuaTPDG {
            get {
                return ResourceManager.GetString("mes_SuaTPDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải dữ liệu thành công.
        /// </summary>
        public static string mes_TaiThanhCong {
            get {
                return ResourceManager.GetString("mes_TaiThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thêm công cụ đánh giá và thời điểm đánh giá vào bảng.
        /// </summary>
        public static string mes_ThemCCDG {
            get {
                return ResourceManager.GetString("mes_ThemCCDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thêm hoạt động thành công.
        /// </summary>
        public static string mes_ThemHoatDong {
            get {
                return ResourceManager.GetString("mes_ThemHoatDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thêm Kết quả học tập mong đợi vào bảng.
        /// </summary>
        public static string mes_ThemKQHT {
            get {
                return ResourceManager.GetString("mes_ThemKQHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thêm thành phần đánh giá vào bảng.
        /// </summary>
        public static string mes_ThemTPDG {
            get {
                return ResourceManager.GetString("mes_ThemTPDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng trọng số phải bằng 100%.
        /// </summary>
        public static string mes_TongPhaiBang100 {
            get {
                return ResourceManager.GetString("mes_TongPhaiBang100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập thời hạn nộp đề cương không đúng.
        /// </summary>
        public static string mes_Trong {
            get {
                return ResourceManager.GetString("mes_Trong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã từ chối phê duyệt đề cương học phần.
        /// </summary>
        public static string mes_TuChoiPheDuyet {
            get {
                return ResourceManager.GetString("mes_TuChoiPheDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đề cương đã bị từ chối phê duyệt.
        /// </summary>
        public static string mes_TuChoiPheDuyetDC {
            get {
                return ResourceManager.GetString("mes_TuChoiPheDuyetDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa tài liệu khỏi bảng.
        /// </summary>
        public static string mes_XoaBang {
            get {
                return ResourceManager.GetString("mes_XoaBang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa buổi học.
        /// </summary>
        public static string mes_XoaBuoi {
            get {
                return ResourceManager.GetString("mes_XoaBuoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa công cụ và thời điểm đánh giá.
        /// </summary>
        public static string mes_XoaCCDG {
            get {
                return ResourceManager.GetString("mes_XoaCCDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xoá hoạt động.
        /// </summary>
        public static string mes_XoaHoatDong {
            get {
                return ResourceManager.GetString("mes_XoaHoatDong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa Kết quả học tập mong đợi khỏi bảng.
        /// </summary>
        public static string mes_XoaKQHT {
            get {
                return ResourceManager.GetString("mes_XoaKQHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xoá mức độ.
        /// </summary>
        public static string mes_XoaMucDo {
            get {
                return ResourceManager.GetString("mes_XoaMucDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa nội dung.
        /// </summary>
        public static string mes_XoaND {
            get {
                return ResourceManager.GetString("mes_XoaND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa tài liệu khỏi bảng.
        /// </summary>
        public static string mes_XoaTaiLieu {
            get {
                return ResourceManager.GetString("mes_XoaTaiLieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string role_Admin {
            get {
                return ResourceManager.GetString("role_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảng viên.
        /// </summary>
        public static string role_GiangVien {
            get {
                return ResourceManager.GetString("role_GiangVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảng viên cơ hữu.
        /// </summary>
        public static string role_GiangVienCoHuu {
            get {
                return ResourceManager.GetString("role_GiangVienCoHuu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảng viên thỉnh giảng.
        /// </summary>
        public static string role_GiangVienThinhGiang {
            get {
                return ResourceManager.GetString("role_GiangVienThinhGiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trợ lý giáo vụ khoa.
        /// </summary>
        public static string role_TroLyGiaoVuKhoa {
            get {
                return ResourceManager.GetString("role_TroLyGiaoVuKhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trưởng bộ môn.
        /// </summary>
        public static string role_TruongBoMon {
            get {
                return ResourceManager.GetString("role_TruongBoMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảng viên.
        /// </summary>
        public static string var_GiangVien {
            get {
                return ResourceManager.GetString("var_GiangVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiến thức chuyên ngành.
        /// </summary>
        public static string var_KienThucChuyenNganh {
            get {
                return ResourceManager.GetString("var_KienThucChuyenNganh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiến thức cơ sở ngành.
        /// </summary>
        public static string var_KienThucCoSoNganh {
            get {
                return ResourceManager.GetString("var_KienThucCoSoNganh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm sinh viên.
        /// </summary>
        public static string var_NhomSinhVien {
            get {
                return ResourceManager.GetString("var_NhomSinhVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinh viên.
        /// </summary>
        public static string var_SinhVien {
            get {
                return ResourceManager.GetString("var_SinhVien", resourceCulture);
            }
        }
    }
}
