//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Areas.CMS.NotificationManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Capstone.Areas.CMS.NotificationManagement.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa cấu hình không thành công, vui lòng thử lại !.
        /// </summary>
        internal static string CH_Suadulieu {
            get {
                return ResourceManager.GetString("CH_Suadulieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa không thành công, vui lòng thử lại !.
        /// </summary>
        internal static string DCCT_Chinhsuadulieu {
            get {
                return ResourceManager.GetString("DCCT_Chinhsuadulieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi hiển thị dữ liệu, vui lòng thử lại !.
        /// </summary>
        internal static string DCCT_LoadData {
            get {
                return ResourceManager.GetString("DCCT_LoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu không thành công, vui lòng thử lại !.
        /// </summary>
        internal static string DCCT_Luudulieu {
            get {
                return ResourceManager.GetString("DCCT_Luudulieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa không thành công, vui lòng thử lại !.
        /// </summary>
        internal static string DCCT_Xoadulieu {
            get {
                return ResourceManager.GetString("DCCT_Xoadulieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa không thành công, vui lòng thử lại !.
        /// </summary>
        internal static string DM_Chinhsuadulieu {
            get {
                return ResourceManager.GetString("DM_Chinhsuadulieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu không thành công, vui lòng thử lại !.
        /// </summary>
        internal static string DM_Luudulieu {
            get {
                return ResourceManager.GetString("DM_Luudulieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa không thành công, vui lòng thử lại !.
        /// </summary>
        internal static string DM_Xoadulieu {
            get {
                return ResourceManager.GetString("DM_Xoadulieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng thử lại !.
        /// </summary>
        internal static string LoadData {
            get {
                return ResourceManager.GetString("LoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa CTĐT Khung không thành công! Vui lòng thử lại!.
        /// </summary>
        internal static string LoichinhsuaCTDTkhung {
            get {
                return ResourceManager.GetString("LoichinhsuaCTDTkhung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa học phần không thành công! Vui lòng thử lại!.
        /// </summary>
        internal static string Loichinhsuahocphan {
            get {
                return ResourceManager.GetString("Loichinhsuahocphan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa kết quả học tập mong đợi không thành công! Vui lòng thử lại!.
        /// </summary>
        internal static string LoichinhsuaketquahoctapmongdoiCTDTkhung {
            get {
                return ResourceManager.GetString("LoichinhsuaketquahoctapmongdoiCTDTkhung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa mục tiêu đào tạo không thành công! Vui lòng thử lại!.
        /// </summary>
        internal static string LoichinhsuamuctieudaotaocutheCTDTkhung {
            get {
                return ResourceManager.GetString("LoichinhsuamuctieudaotaocutheCTDTkhung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra! Vui lòng thử lại!.
        /// </summary>
        internal static string Loichung {
            get {
                return ResourceManager.GetString("Loichung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu ! Vui lòng thêm dữ liệu..
        /// </summary>
        internal static string Loikhongdulieu {
            get {
                return ResourceManager.GetString("Loikhongdulieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới CTĐT Khung không thành công! Vui lòng thử lại!.
        /// </summary>
        internal static string LoithemmoiCTDTkhung {
            get {
                return ResourceManager.GetString("LoithemmoiCTDTkhung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới học phần không thành công! Vui lòng thử lại!.
        /// </summary>
        internal static string Loithemmoihocphan {
            get {
                return ResourceManager.GetString("Loithemmoihocphan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới kết quả học tập mong đợi không thành công! Vui lòng thử lại!.
        /// </summary>
        internal static string LoithemmoiketquahoctapmongdoiCTDTkhung {
            get {
                return ResourceManager.GetString("LoithemmoiketquahoctapmongdoiCTDTkhung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới mục tiêu đào tạo cụ thể không thành công! Vui lòng thử lại!.
        /// </summary>
        internal static string LoithemmoimuctieudaotaocutheCTDTkhung {
            get {
                return ResourceManager.GetString("LoithemmoimuctieudaotaocutheCTDTkhung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa học phần không thành công! Vui lòng thử lại!.
        /// </summary>
        internal static string Loixoahocphan {
            get {
                return ResourceManager.GetString("Loixoahocphan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa kết quả học tập mong đợi không thành công! Vui lòng thử lại!.
        /// </summary>
        internal static string LoixoaketquahoctapmongdoiCTDTkhung {
            get {
                return ResourceManager.GetString("LoixoaketquahoctapmongdoiCTDTkhung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa mục tiêu đào tạo cụ thể không thành công! Vui lòng thử lại!.
        /// </summary>
        internal static string LoixoamuctieudaotaocutheCTDTkhung {
            get {
                return ResourceManager.GetString("LoixoamuctieudaotaocutheCTDTkhung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa người dùng không thành công, vui lòng thử lại !.
        /// </summary>
        internal static string ND_Suadulieu {
            get {
                return ResourceManager.GetString("ND_Suadulieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa nhân viên không thành công, vui lòng thử lại !.
        /// </summary>
        internal static string NV_Chinhsuadulieu {
            get {
                return ResourceManager.GetString("NV_Chinhsuadulieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu không thành công, vui lòng thử lại !.
        /// </summary>
        internal static string NV_Luudulieu {
            get {
                return ResourceManager.GetString("NV_Luudulieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa không thành công, vui lòng thử lại !.
        /// </summary>
        internal static string NV_Xoadulieu {
            get {
                return ResourceManager.GetString("NV_Xoadulieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy chương trình đào tạo khung phù hợp.
        /// </summary>
        internal static string TimCTDT {
            get {
                return ResourceManager.GetString("TimCTDT", resourceCulture);
            }
        }
    }
}
