//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Areas.CMS.NotificationManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SuccessMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SuccessMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Capstone.Areas.CMS.NotificationManagement.SuccessMessage", typeof(SuccessMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xóa môn học?.
        /// </summary>
        internal static string Bancomuonxoahocphan {
            get {
                return ResourceManager.GetString("Bancomuonxoahocphan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xóa kết quả học tập mong đợi?.
        /// </summary>
        internal static string Bancomuonxoaketquahoctapmongdoi {
            get {
                return ResourceManager.GetString("Bancomuonxoaketquahoctapmongdoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn xóa mục tiêu đào tạo cụ thể?.
        /// </summary>
        internal static string Bancomuonxoamuctieudaotaocuthe {
            get {
                return ResourceManager.GetString("Bancomuonxoamuctieudaotaocuthe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa cấu hình thành công !.
        /// </summary>
        internal static string CH_Suacauhinh {
            get {
                return ResourceManager.GetString("CH_Suacauhinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa CTĐT Khung thành công!.
        /// </summary>
        internal static string ChinhsuaCTDTkhungthanhcong {
            get {
                return ResourceManager.GetString("ChinhsuaCTDTkhungthanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa học phần thành công!.
        /// </summary>
        internal static string Chinhsuahocphanthanhcong {
            get {
                return ResourceManager.GetString("Chinhsuahocphanthanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa kết quả học tập mong đợi thành công!.
        /// </summary>
        internal static string Chinhsuaketquahoctapmongdoithanhcong {
            get {
                return ResourceManager.GetString("Chinhsuaketquahoctapmongdoithanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa mục tiêu đào tạo cụ thể thành công!.
        /// </summary>
        internal static string Chinhsuamuctieudaotaocuthethanhcong {
            get {
                return ResourceManager.GetString("Chinhsuamuctieudaotaocuthethanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá CTĐT Khung thành công!.
        /// </summary>
        internal static string DanhgiaCTDTkhungthanhcong {
            get {
                return ResourceManager.GetString("DanhgiaCTDTkhungthanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu nội dung đánh giá thành công !.
        /// </summary>
        internal static string DCCT_Danhgia {
            get {
                return ResourceManager.GetString("DCCT_Danhgia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xây dựng đề cương thành công !.
        /// </summary>
        internal static string DCCT_Hoanthanh {
            get {
                return ResourceManager.GetString("DCCT_Hoanthanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu tạm đề cương thành công !.
        /// </summary>
        internal static string DCCT_Luutam {
            get {
                return ResourceManager.GetString("DCCT_Luutam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa kết quả học tập mong đợi thành công !.
        /// </summary>
        internal static string DCCT_SuaCDR {
            get {
                return ResourceManager.GetString("DCCT_SuaCDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa nội dung giảng dạy thành công !.
        /// </summary>
        internal static string DCCT_SuaND {
            get {
                return ResourceManager.GetString("DCCT_SuaND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa tài liệu thành công !.
        /// </summary>
        internal static string DCCT_SuaTL {
            get {
                return ResourceManager.GetString("DCCT_SuaTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm kết quả học tập mong đợi thành công !.
        /// </summary>
        internal static string DCCT_ThemCDR {
            get {
                return ResourceManager.GetString("DCCT_ThemCDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nôị dung giảng dạy thành công !.
        /// </summary>
        internal static string DCCT_ThemND {
            get {
                return ResourceManager.GetString("DCCT_ThemND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm tài liệu thành công !.
        /// </summary>
        internal static string DCCT_ThemTL {
            get {
                return ResourceManager.GetString("DCCT_ThemTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa kết quả học tập mong đợi thành công !.
        /// </summary>
        internal static string DCCT_XoaCDR {
            get {
                return ResourceManager.GetString("DCCT_XoaCDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nội dung giảng dạy thành công !.
        /// </summary>
        internal static string DCCT_XoaND {
            get {
                return ResourceManager.GetString("DCCT_XoaND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa tài liệu thành công !.
        /// </summary>
        internal static string DCCT_XoaTL {
            get {
                return ResourceManager.GetString("DCCT_XoaTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu biểu mẫu email thành công !.
        /// </summary>
        internal static string DM_Luumail {
            get {
                return ResourceManager.GetString("DM_Luumail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa hệ ngành thành công !.
        /// </summary>
        internal static string DM_Suahenganh {
            get {
                return ResourceManager.GetString("DM_Suahenganh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa khoa thành công !.
        /// </summary>
        internal static string DM_Suakhoa {
            get {
                return ResourceManager.GetString("DM_Suakhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa khối kiến thức thành công !.
        /// </summary>
        internal static string DM_Suakhoikienthuc {
            get {
                return ResourceManager.GetString("DM_Suakhoikienthuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa khối lớp thành công !.
        /// </summary>
        internal static string DM_Suakhoilop {
            get {
                return ResourceManager.GetString("DM_Suakhoilop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa biểu mẫu email thành công !.
        /// </summary>
        internal static string DM_Suamail {
            get {
                return ResourceManager.GetString("DM_Suamail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm hệ ngành thành công !.
        /// </summary>
        internal static string DM_Themhenganh {
            get {
                return ResourceManager.GetString("DM_Themhenganh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm khoa thành công !.
        /// </summary>
        internal static string DM_Themkhoa {
            get {
                return ResourceManager.GetString("DM_Themkhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm khối kiến thức thành công !.
        /// </summary>
        internal static string DM_Themkhoikienthuc {
            get {
                return ResourceManager.GetString("DM_Themkhoikienthuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm khối lớp thành công !.
        /// </summary>
        internal static string DM_Themkhoilop {
            get {
                return ResourceManager.GetString("DM_Themkhoilop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm biểu mẫu email thành công !.
        /// </summary>
        internal static string DM_Themmail {
            get {
                return ResourceManager.GetString("DM_Themmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa khoa thành công !.
        /// </summary>
        internal static string DM_Xoakhoa {
            get {
                return ResourceManager.GetString("DM_Xoakhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa biểu mẫu email thành công !.
        /// </summary>
        internal static string DM_Xoamail {
            get {
                return ResourceManager.GetString("DM_Xoamail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa giảng viên thành công !.
        /// </summary>
        internal static string KH_Suagv {
            get {
                return ResourceManager.GetString("KH_Suagv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo thành công mục tiêu đào tạo cụ thể!.
        /// </summary>
        internal static string KH_Themmuctieu {
            get {
                return ResourceManager.GetString("KH_Themmuctieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu ma trận thành công!.
        /// </summary>
        internal static string Luumatranthanhcong {
            get {
                return ResourceManager.GetString("Luumatranthanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa người dùng thành công !.
        /// </summary>
        internal static string ND_Suand {
            get {
                return ResourceManager.GetString("ND_Suand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa nhân viên thành công !.
        /// </summary>
        internal static string NV_Suanv {
            get {
                return ResourceManager.GetString("NV_Suanv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhân viên thành công !.
        /// </summary>
        internal static string NV_Themnv {
            get {
                return ResourceManager.GetString("NV_Themnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nhân viên thành công !.
        /// </summary>
        internal static string NV_Xoanv {
            get {
                return ResourceManager.GetString("NV_Xoanv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa giảng viên thành công !.
        /// </summary>
        internal static string Suagv {
            get {
                return ResourceManager.GetString("Suagv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới CTĐT Khung thành công!.
        /// </summary>
        internal static string TaoCTDTkhungthanhcong {
            get {
                return ResourceManager.GetString("TaoCTDTkhungthanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Chương trình đào tạo thành công !.
        /// </summary>
        internal static string ThemCTDTKH {
            get {
                return ResourceManager.GetString("ThemCTDTKH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm giảng viên thành công !.
        /// </summary>
        internal static string Themgv {
            get {
                return ResourceManager.GetString("Themgv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới môn học thành công!.
        /// </summary>
        internal static string Themmoihocphanthanhcong {
            get {
                return ResourceManager.GetString("Themmoihocphanthanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới kết quả học tập mong đợi CTĐT Khung thành công!.
        /// </summary>
        internal static string ThemmoiketquahoctapmongdoiCTDTkhungthanhcong {
            get {
                return ResourceManager.GetString("ThemmoiketquahoctapmongdoiCTDTkhungthanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới mục tiêu đào tạo cụ thể thành công!.
        /// </summary>
        internal static string ThemmoimuctieudaotaocutheCTDTkhungthanhcong {
            get {
                return ResourceManager.GetString("ThemmoimuctieudaotaocutheCTDTkhungthanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa học phần thành công!.
        /// </summary>
        internal static string Xoahocphanthanhcong {
            get {
                return ResourceManager.GetString("Xoahocphanthanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa kết quả học tập mong đợi CTĐT Khung thành công!.
        /// </summary>
        internal static string XoaketquahoctapmongdoiCTDTkhungthanhcong {
            get {
                return ResourceManager.GetString("XoaketquahoctapmongdoiCTDTkhungthanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa mục tiêu đào tạo cụ thể CTĐT Khung thành công!.
        /// </summary>
        internal static string XoamuctieudaotaocutheCTDTkhungthanhcong {
            get {
                return ResourceManager.GetString("XoamuctieudaotaocutheCTDTkhungthanhcong", resourceCulture);
            }
        }
    }
}
