//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class fit_misDBEntities : DbContext
    {
        public fit_misDBEntities()
            : base("name=fit_misDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<m_Nhanvien> m_Nhanvien { get; set; }
        public virtual DbSet<sc_HeNganh> sc_HeNganh { get; set; }
        public virtual DbSet<sc_Hocphan> sc_Hocphan { get; set; }
        public virtual DbSet<sc_Khoa> sc_Khoa { get; set; }
        public virtual DbSet<sc_Khoikienthuc> sc_Khoikienthuc { get; set; }
        public virtual DbSet<sc_Khoilop> sc_Khoilop { get; set; }
        public virtual DbSet<sc_LoaiPH> sc_LoaiPH { get; set; }
        public virtual DbSet<sc_Ma> sc_Ma { get; set; }
        public virtual DbSet<sf_EmailTemplate> sf_EmailTemplate { get; set; }
        public virtual DbSet<sf_LogHistory> sf_LogHistory { get; set; }
        public virtual DbSet<sf_Notification> sf_Notification { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<t_CDR_CTDT> t_CDR_CTDT { get; set; }
        public virtual DbSet<t_CTDaotao> t_CTDaotao { get; set; }
        public virtual DbSet<t_MT_CTDT> t_MT_CTDT { get; set; }
        public virtual DbSet<tc_CDR_HP> tc_CDR_HP { get; set; }
        public virtual DbSet<tc_DecuongGV> tc_DecuongGV { get; set; }
        public virtual DbSet<tc_KHDaotao> tc_KHDaotao { get; set; }
        public virtual DbSet<tc_MatranCDR> tc_MatranCDR { get; set; }
        public virtual DbSet<tc_NoidungHP> tc_NoidungHP { get; set; }
        public virtual DbSet<tc_TailieuHP> tc_TailieuHP { get; set; }
        public virtual DbSet<tp_CDR_HP> tp_CDR_HP { get; set; }
        public virtual DbSet<tp_ChitietHP> tp_ChitietHP { get; set; }
        public virtual DbSet<tp_DanhgiaHP> tp_DanhgiaHP { get; set; }
        public virtual DbSet<tp_DecuongGV> tp_DecuongGV { get; set; }
        public virtual DbSet<tp_KHDaotao> tp_KHDaotao { get; set; }
        public virtual DbSet<tp_Lop_ChitietHP> tp_Lop_ChitietHP { get; set; }
        public virtual DbSet<tp_LopHP> tp_LopHP { get; set; }
        public virtual DbSet<tp_LopSV> tp_LopSV { get; set; }
        public virtual DbSet<tp_Lop_TacvuHP> tp_Lop_TacvuHP { get; set; }
        public virtual DbSet<tp_MatranCDR> tp_MatranCDR { get; set; }
        public virtual DbSet<tp_NoidungHP> tp_NoidungHP { get; set; }
        public virtual DbSet<tp_TacvuHP> tp_TacvuHP { get; set; }
        public virtual DbSet<tp_TailieuHP> tp_TailieuHP { get; set; }
        public virtual DbSet<tp_TieuchiDG> tp_TieuchiDG { get; set; }
        public virtual DbSet<tp_TKB> tp_TKB { get; set; }
    
        [DbFunction("fit_misDBEntities", "LevelFirst")]
        public virtual IQueryable<LevelFirst_Result> LevelFirst(Nullable<int> makhdt)
        {
            var makhdtParameter = makhdt.HasValue ?
                new ObjectParameter("makhdt", makhdt) :
                new ObjectParameter("makhdt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<LevelFirst_Result>("[fit_misDBEntities].[LevelFirst](@makhdt)", makhdtParameter);
        }
    
        [DbFunction("fit_misDBEntities", "LevelSecond")]
        public virtual IQueryable<LevelSecond_Result> LevelSecond(Nullable<int> makhdt)
        {
            var makhdtParameter = makhdt.HasValue ?
                new ObjectParameter("makhdt", makhdt) :
                new ObjectParameter("makhdt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<LevelSecond_Result>("[fit_misDBEntities].[LevelSecond](@makhdt)", makhdtParameter);
        }
    
        [DbFunction("fit_misDBEntities", "LevelThird")]
        public virtual IQueryable<LevelThird_Result> LevelThird(Nullable<int> makhdt)
        {
            var makhdtParameter = makhdt.HasValue ?
                new ObjectParameter("makhdt", makhdt) :
                new ObjectParameter("makhdt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<LevelThird_Result>("[fit_misDBEntities].[LevelThird](@makhdt)", makhdtParameter);
        }
    
        [DbFunction("fit_misDBEntities", "SDF_SplitString")]
        public virtual IQueryable<SDF_SplitString_Result> SDF_SplitString(string sString, string cDelimiter)
        {
            var sStringParameter = sString != null ?
                new ObjectParameter("sString", sString) :
                new ObjectParameter("sString", typeof(string));
    
            var cDelimiterParameter = cDelimiter != null ?
                new ObjectParameter("cDelimiter", cDelimiter) :
                new ObjectParameter("cDelimiter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SDF_SplitString_Result>("[fit_misDBEntities].[SDF_SplitString](@sString, @cDelimiter)", sStringParameter, cDelimiterParameter);
        }
    
        public virtual int ARDataLopCTHP(string namhoc, string hocky, Nullable<int> mahn)
        {
            var namhocParameter = namhoc != null ?
                new ObjectParameter("namhoc", namhoc) :
                new ObjectParameter("namhoc", typeof(string));
    
            var hockyParameter = hocky != null ?
                new ObjectParameter("hocky", hocky) :
                new ObjectParameter("hocky", typeof(string));
    
            var mahnParameter = mahn.HasValue ?
                new ObjectParameter("mahn", mahn) :
                new ObjectParameter("mahn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ARDataLopCTHP", namhocParameter, hockyParameter, mahnParameter);
        }
    
        public virtual int ARDataLopTVDanhGiaHP(string namhoc, string hocky, Nullable<int> mahn)
        {
            var namhocParameter = namhoc != null ?
                new ObjectParameter("namhoc", namhoc) :
                new ObjectParameter("namhoc", typeof(string));
    
            var hockyParameter = hocky != null ?
                new ObjectParameter("hocky", hocky) :
                new ObjectParameter("hocky", typeof(string));
    
            var mahnParameter = mahn.HasValue ?
                new ObjectParameter("mahn", mahn) :
                new ObjectParameter("mahn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ARDataLopTVDanhGiaHP", namhocParameter, hockyParameter, mahnParameter);
        }
    
        public virtual int ChangeStatusUpdate(string namhoc, string hocky, Nullable<int> mahn)
        {
            var namhocParameter = namhoc != null ?
                new ObjectParameter("namhoc", namhoc) :
                new ObjectParameter("namhoc", typeof(string));
    
            var hockyParameter = hocky != null ?
                new ObjectParameter("hocky", hocky) :
                new ObjectParameter("hocky", typeof(string));
    
            var mahnParameter = mahn.HasValue ?
                new ObjectParameter("mahn", mahn) :
                new ObjectParameter("mahn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ChangeStatusUpdate", namhocParameter, hockyParameter, mahnParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CheckParallel(string namhoc, string hocky, Nullable<int> mahn)
        {
            var namhocParameter = namhoc != null ?
                new ObjectParameter("namhoc", namhoc) :
                new ObjectParameter("namhoc", typeof(string));
    
            var hockyParameter = hocky != null ?
                new ObjectParameter("hocky", hocky) :
                new ObjectParameter("hocky", typeof(string));
    
            var mahnParameter = mahn.HasValue ?
                new ObjectParameter("mahn", mahn) :
                new ObjectParameter("mahn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CheckParallel", namhocParameter, hockyParameter, mahnParameter);
        }
    
        public virtual ObjectResult<ClassTeacher_Result> ClassTeacher(string namhoc, string hocky, Nullable<int> mahn, string idUser)
        {
            var namhocParameter = namhoc != null ?
                new ObjectParameter("namhoc", namhoc) :
                new ObjectParameter("namhoc", typeof(string));
    
            var hockyParameter = hocky != null ?
                new ObjectParameter("hocky", hocky) :
                new ObjectParameter("hocky", typeof(string));
    
            var mahnParameter = mahn.HasValue ?
                new ObjectParameter("mahn", mahn) :
                new ObjectParameter("mahn", typeof(int));
    
            var idUserParameter = idUser != null ?
                new ObjectParameter("idUser", idUser) :
                new ObjectParameter("idUser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ClassTeacher_Result>("ClassTeacher", namhocParameter, hockyParameter, mahnParameter, idUserParameter);
        }
    
        public virtual int clearPurepose(Nullable<int> makhdt)
        {
            var makhdtParameter = makhdt.HasValue ?
                new ObjectParameter("makhdt", makhdt) :
                new ObjectParameter("makhdt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("clearPurepose", makhdtParameter);
        }
    
        public virtual int CreateKHDTIC(Nullable<int> maKHDTPC, string namHocIC, string hocKyIC, Nullable<System.DateTime> ngayBDIC, Nullable<System.DateTime> ngayKTIC, Nullable<System.DateTime> ngayHT, Nullable<int> maKhoiIC)
        {
            var maKHDTPCParameter = maKHDTPC.HasValue ?
                new ObjectParameter("maKHDTPC", maKHDTPC) :
                new ObjectParameter("maKHDTPC", typeof(int));
    
            var namHocICParameter = namHocIC != null ?
                new ObjectParameter("namHocIC", namHocIC) :
                new ObjectParameter("namHocIC", typeof(string));
    
            var hocKyICParameter = hocKyIC != null ?
                new ObjectParameter("hocKyIC", hocKyIC) :
                new ObjectParameter("hocKyIC", typeof(string));
    
            var ngayBDICParameter = ngayBDIC.HasValue ?
                new ObjectParameter("ngayBDIC", ngayBDIC) :
                new ObjectParameter("ngayBDIC", typeof(System.DateTime));
    
            var ngayKTICParameter = ngayKTIC.HasValue ?
                new ObjectParameter("ngayKTIC", ngayKTIC) :
                new ObjectParameter("ngayKTIC", typeof(System.DateTime));
    
            var ngayHTParameter = ngayHT.HasValue ?
                new ObjectParameter("ngayHT", ngayHT) :
                new ObjectParameter("ngayHT", typeof(System.DateTime));
    
            var maKhoiICParameter = maKhoiIC.HasValue ?
                new ObjectParameter("maKhoiIC", maKhoiIC) :
                new ObjectParameter("maKhoiIC", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateKHDTIC", maKHDTPCParameter, namHocICParameter, hocKyICParameter, ngayBDICParameter, ngayKTICParameter, ngayHTParameter, maKhoiICParameter);
        }
    
        public virtual int CrItemLopHP(string maKHDT, string tenlop, string ghichu, string dSSVPath, string maGV, string tietBD, string tietKT, string phongHoc, string thu, string buoi)
        {
            var maKHDTParameter = maKHDT != null ?
                new ObjectParameter("MaKHDT", maKHDT) :
                new ObjectParameter("MaKHDT", typeof(string));
    
            var tenlopParameter = tenlop != null ?
                new ObjectParameter("Tenlop", tenlop) :
                new ObjectParameter("Tenlop", typeof(string));
    
            var ghichuParameter = ghichu != null ?
                new ObjectParameter("Ghichu", ghichu) :
                new ObjectParameter("Ghichu", typeof(string));
    
            var dSSVPathParameter = dSSVPath != null ?
                new ObjectParameter("DSSVPath", dSSVPath) :
                new ObjectParameter("DSSVPath", typeof(string));
    
            var maGVParameter = maGV != null ?
                new ObjectParameter("MaGV", maGV) :
                new ObjectParameter("MaGV", typeof(string));
    
            var tietBDParameter = tietBD != null ?
                new ObjectParameter("TietBD", tietBD) :
                new ObjectParameter("TietBD", typeof(string));
    
            var tietKTParameter = tietKT != null ?
                new ObjectParameter("TietKT", tietKT) :
                new ObjectParameter("TietKT", typeof(string));
    
            var phongHocParameter = phongHoc != null ?
                new ObjectParameter("PhongHoc", phongHoc) :
                new ObjectParameter("PhongHoc", typeof(string));
    
            var thuParameter = thu != null ?
                new ObjectParameter("Thu", thu) :
                new ObjectParameter("Thu", typeof(string));
    
            var buoiParameter = buoi != null ?
                new ObjectParameter("Buoi", buoi) :
                new ObjectParameter("Buoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrItemLopHP", maKHDTParameter, tenlopParameter, ghichuParameter, dSSVPathParameter, maGVParameter, tietBDParameter, tietKTParameter, phongHocParameter, thuParameter, buoiParameter);
        }
    
        public virtual int delData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delData");
        }
    
        public virtual int ErazerLop(string namhoc, string hocky, Nullable<int> mahn)
        {
            var namhocParameter = namhoc != null ?
                new ObjectParameter("namhoc", namhoc) :
                new ObjectParameter("namhoc", typeof(string));
    
            var hockyParameter = hocky != null ?
                new ObjectParameter("hocky", hocky) :
                new ObjectParameter("hocky", typeof(string));
    
            var mahnParameter = mahn.HasValue ?
                new ObjectParameter("mahn", mahn) :
                new ObjectParameter("mahn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ErazerLop", namhocParameter, hockyParameter, mahnParameter);
        }
    
        public virtual ObjectResult<GetGiangVienGoiY_Result> GetGiangVienGoiY(Nullable<int> maKHDT)
        {
            var maKHDTParameter = maKHDT.HasValue ?
                new ObjectParameter("MaKHDT", maKHDT) :
                new ObjectParameter("MaKHDT", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetGiangVienGoiY_Result>("GetGiangVienGoiY", maKHDTParameter);
        }
    
        public virtual ObjectResult<GetListAction_Result> GetListAction(Nullable<int> makhdt)
        {
            var makhdtParameter = makhdt.HasValue ?
                new ObjectParameter("makhdt", makhdt) :
                new ObjectParameter("makhdt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetListAction_Result>("GetListAction", makhdtParameter);
        }
    
        public virtual ObjectResult<GetListCDR_NoiDung_TacVu_Result> GetListCDR_NoiDung_TacVu(Nullable<int> makhdt, Nullable<int> macelo, Nullable<int> mand)
        {
            var makhdtParameter = makhdt.HasValue ?
                new ObjectParameter("makhdt", makhdt) :
                new ObjectParameter("makhdt", typeof(int));
    
            var maceloParameter = macelo.HasValue ?
                new ObjectParameter("macelo", macelo) :
                new ObjectParameter("macelo", typeof(int));
    
            var mandParameter = mand.HasValue ?
                new ObjectParameter("mand", mand) :
                new ObjectParameter("mand", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetListCDR_NoiDung_TacVu_Result>("GetListCDR_NoiDung_TacVu", makhdtParameter, maceloParameter, mandParameter);
        }
    
        public virtual ObjectResult<GetListNoiDung_Result> GetListNoiDung(Nullable<int> makhdt)
        {
            var makhdtParameter = makhdt.HasValue ?
                new ObjectParameter("makhdt", makhdt) :
                new ObjectParameter("makhdt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetListNoiDung_Result>("GetListNoiDung", makhdtParameter);
        }
    
        public virtual ObjectResult<GetListTeacherCurrent_Result> GetListTeacherCurrent(string semester, string year)
        {
            var semesterParameter = semester != null ?
                new ObjectParameter("semester", semester) :
                new ObjectParameter("semester", typeof(string));
    
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetListTeacherCurrent_Result>("GetListTeacherCurrent", semesterParameter, yearParameter);
        }
    
        public virtual ObjectResult<GetProDetailCurrent_Result> GetProDetailCurrent(string semester, string year)
        {
            var semesterParameter = semester != null ?
                new ObjectParameter("semester", semester) :
                new ObjectParameter("semester", typeof(string));
    
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProDetailCurrent_Result>("GetProDetailCurrent", semesterParameter, yearParameter);
        }
    
        public virtual ObjectResult<GetRoleGVHocPhan_Result> GetRoleGVHocPhan(Nullable<int> makhdt)
        {
            var makhdtParameter = makhdt.HasValue ?
                new ObjectParameter("makhdt", makhdt) :
                new ObjectParameter("makhdt", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRoleGVHocPhan_Result>("GetRoleGVHocPhan", makhdtParameter);
        }
    
        public virtual ObjectResult<GetTeacherSchedule_Result> GetTeacherSchedule(string namhoc, string hocky, Nullable<int> mahn)
        {
            var namhocParameter = namhoc != null ?
                new ObjectParameter("namhoc", namhoc) :
                new ObjectParameter("namhoc", typeof(string));
    
            var hockyParameter = hocky != null ?
                new ObjectParameter("hocky", hocky) :
                new ObjectParameter("hocky", typeof(string));
    
            var mahnParameter = mahn.HasValue ?
                new ObjectParameter("mahn", mahn) :
                new ObjectParameter("mahn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTeacherSchedule_Result>("GetTeacherSchedule", namhocParameter, hockyParameter, mahnParameter);
        }
    
        public virtual ObjectResult<GetTeaMail_Result> GetTeaMail(string namhoc, string hocky, Nullable<int> mahn)
        {
            var namhocParameter = namhoc != null ?
                new ObjectParameter("namhoc", namhoc) :
                new ObjectParameter("namhoc", typeof(string));
    
            var hockyParameter = hocky != null ?
                new ObjectParameter("hocky", hocky) :
                new ObjectParameter("hocky", typeof(string));
    
            var mahnParameter = mahn.HasValue ?
                new ObjectParameter("mahn", mahn) :
                new ObjectParameter("mahn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTeaMail_Result>("GetTeaMail", namhocParameter, hockyParameter, mahnParameter);
        }
    
        public virtual ObjectResult<pr_GetGroupLevel_Result> pr_GetGroupLevel(Nullable<int> makhdt, Nullable<int> madg)
        {
            var makhdtParameter = makhdt.HasValue ?
                new ObjectParameter("makhdt", makhdt) :
                new ObjectParameter("makhdt", typeof(int));
    
            var madgParameter = madg.HasValue ?
                new ObjectParameter("madg", madg) :
                new ObjectParameter("madg", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_GetGroupLevel_Result>("pr_GetGroupLevel", makhdtParameter, madgParameter);
        }
    
        public virtual ObjectResult<pr_GetGroupTP_Result> pr_GetGroupTP(Nullable<int> makhdt, Nullable<int> madg)
        {
            var makhdtParameter = makhdt.HasValue ?
                new ObjectParameter("makhdt", makhdt) :
                new ObjectParameter("makhdt", typeof(int));
    
            var madgParameter = madg.HasValue ?
                new ObjectParameter("madg", madg) :
                new ObjectParameter("madg", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_GetGroupTP_Result>("pr_GetGroupTP", makhdtParameter, madgParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int SqlQueryNotificationStoredProcedure_2722f9e5_37f7_463a_89f7_876874550eae()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SqlQueryNotificationStoredProcedure_2722f9e5_37f7_463a_89f7_876874550eae");
        }
    
        public virtual ObjectResult<SubjectCurrent_Result> SubjectCurrent(string namhoc, string hocky, Nullable<int> mahn)
        {
            var namhocParameter = namhoc != null ?
                new ObjectParameter("namhoc", namhoc) :
                new ObjectParameter("namhoc", typeof(string));
    
            var hockyParameter = hocky != null ?
                new ObjectParameter("hocky", hocky) :
                new ObjectParameter("hocky", typeof(string));
    
            var mahnParameter = mahn.HasValue ?
                new ObjectParameter("mahn", mahn) :
                new ObjectParameter("mahn", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SubjectCurrent_Result>("SubjectCurrent", namhocParameter, hockyParameter, mahnParameter);
        }
    }
}
