//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sc_HeNganh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sc_HeNganh()
        {
            this.sc_HeNganh1 = new HashSet<sc_HeNganh>();
            this.t_CTDaotao = new HashSet<t_CTDaotao>();
        }
    
        public int MaHN { get; set; }
        public int MaKhoa { get; set; }
        public string Mota { get; set; }
        public string Tenrutgon { get; set; }
        public string MaDK { get; set; }
        public Nullable<int> MaQH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sc_HeNganh> sc_HeNganh1 { get; set; }
        public virtual sc_HeNganh sc_HeNganh2 { get; set; }
        public virtual sc_Khoa sc_Khoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_CTDaotao> t_CTDaotao { get; set; }
    }
}
