//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sc_Khoikienthuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sc_Khoikienthuc()
        {
            this.sc_Khoikienthuc1 = new HashSet<sc_Khoikienthuc>();
            this.tc_KHDaotao = new HashSet<tc_KHDaotao>();
        }
    
        public int MaKhoiKT { get; set; }
        public string Mota { get; set; }
        public Nullable<int> MaQH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sc_Khoikienthuc> sc_Khoikienthuc1 { get; set; }
        public virtual sc_Khoikienthuc sc_Khoikienthuc2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tc_KHDaotao> tc_KHDaotao { get; set; }
    }
}
