//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sc_Ma
    {
        public int MaCH { get; set; }
        public string LoaiMa { get; set; }
        public string TenMa { get; set; }
        public string Phienban { get; set; }
    }
}
