//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_EmailTemplate
    {
        public int MaET { get; set; }
        public string Chude { get; set; }
        public string Noidung { get; set; }
        public string Phanloai { get; set; }
        public string Ghichu { get; set; }
        public string Khungnoidung { get; set; }
    }
}
