//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_LogHistory
    {
        public int LogId { get; set; }
        public string Mucdo { get; set; }
        public string Nguon { get; set; }
        public string Noidung { get; set; }
        public string Thaotac { get; set; }
        public System.DateTime Ngaytao { get; set; }
        public string Nguoitao { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
