//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sf_Notification
    {
        public int MaTB { get; set; }
        public string Nguon { get; set; }
        public string Thongtin { get; set; }
        public string Kieu { get; set; }
        public string NguoiGui { get; set; }
        public string NguoiNhan { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public Nullable<bool> DaXem { get; set; }
        public Nullable<bool> Trangthai { get; set; }
        public string MaQH { get; set; }
        public string Chude { get; set; }
        public Nullable<int> MaDC { get; set; }
    
        public virtual tc_DecuongGV tc_DecuongGV { get; set; }
    }
}
