//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_CDR_CTDT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_CDR_CTDT()
        {
            this.tc_MatranCDR = new HashSet<tc_MatranCDR>();
            this.tp_MatranCDR = new HashSet<tp_MatranCDR>();
            this.t_MT_CTDT = new HashSet<t_MT_CTDT>();
            this.tc_KHDaotao = new HashSet<tc_KHDaotao>();
        }
    
        public int MaELO { get; set; }
        public int MaCTDT { get; set; }
        public string MaHT { get; set; }
        public string Mota { get; set; }
        public string Phanloai { get; set; }
    
        public virtual t_CTDaotao t_CTDaotao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tc_MatranCDR> tc_MatranCDR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_MatranCDR> tp_MatranCDR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_MT_CTDT> t_MT_CTDT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tc_KHDaotao> tc_KHDaotao { get; set; }
    }
}
