//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_CTDaotao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_CTDaotao()
        {
            this.t_CDR_CTDT = new HashSet<t_CDR_CTDT>();
            this.t_CTDaotao1 = new HashSet<t_CTDaotao>();
            this.t_MT_CTDT = new HashSet<t_MT_CTDT>();
            this.tc_KHDaotao = new HashSet<tc_KHDaotao>();
            this.tp_KHDaotao = new HashSet<tp_KHDaotao>();
        }
    
        public int MaCT { get; set; }
        public int MaHN { get; set; }
        public Nullable<int> MaKhoi { get; set; }
        public Nullable<int> MaTC { get; set; }
        public string TenCT { get; set; }
        public string Muctieu { get; set; }
        public string HinhthucDT { get; set; }
        public string Phienban { get; set; }
        public string LoaiCT { get; set; }
        public string Trinhdo { get; set; }
        public string SoQD { get; set; }
        public Nullable<System.DateTime> NgayQD { get; set; }
        public string ThoigianDT { get; set; }
        public string Doituong { get; set; }
        public string QuytrinhDT { get; set; }
        public string CosoVC { get; set; }
        public string Thangdiem { get; set; }
        public string Khoiluongkienthuc { get; set; }
        public string BanScan { get; set; }
        public string Ghichu { get; set; }
        public string Nguoiduyet { get; set; }
        public Nullable<System.DateTime> Ngayduyet { get; set; }
        public string Tinhtrang { get; set; }
        public string Trangthai { get; set; }
        public Nullable<bool> Xetduyet { get; set; }
    
        public virtual sc_HeNganh sc_HeNganh { get; set; }
        public virtual sc_Khoilop sc_Khoilop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_CDR_CTDT> t_CDR_CTDT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_CTDaotao> t_CTDaotao1 { get; set; }
        public virtual t_CTDaotao t_CTDaotao2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_MT_CTDT> t_MT_CTDT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tc_KHDaotao> tc_KHDaotao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_KHDaotao> tp_KHDaotao { get; set; }
    }
}
