//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_MT_CTDT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_MT_CTDT()
        {
            this.t_CDR_CTDT = new HashSet<t_CDR_CTDT>();
        }
    
        public int MaMT { get; set; }
        public int MaCTDT { get; set; }
        public string Mota { get; set; }
        public string Phanloai { get; set; }
    
        public virtual t_CTDaotao t_CTDaotao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_CDR_CTDT> t_CDR_CTDT { get; set; }
    }
}
