//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_CDR_HP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tc_CDR_HP()
        {
            this.tc_CDR_HP1 = new HashSet<tc_CDR_HP>();
            this.tc_MatranCDR = new HashSet<tc_MatranCDR>();
            this.tc_NoidungHP = new HashSet<tc_NoidungHP>();
        }
    
        public int MaCELO { get; set; }
        public int MaKHDT { get; set; }
        public Nullable<int> MaQH { get; set; }
        public string MaHT { get; set; }
        public string Mota { get; set; }
        public string Phanloai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tc_CDR_HP> tc_CDR_HP1 { get; set; }
        public virtual tc_CDR_HP tc_CDR_HP2 { get; set; }
        public virtual tc_KHDaotao tc_KHDaotao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tc_MatranCDR> tc_MatranCDR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tc_NoidungHP> tc_NoidungHP { get; set; }
    }
}
