//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_KHDaotao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tc_KHDaotao()
        {
            this.tc_CDR_HP = new HashSet<tc_CDR_HP>();
            this.tc_DecuongGV = new HashSet<tc_DecuongGV>();
            this.tc_NoidungHP = new HashSet<tc_NoidungHP>();
            this.tc_TailieuHP = new HashSet<tc_TailieuHP>();
            this.sc_LoaiPH = new HashSet<sc_LoaiPH>();
            this.t_CDR_CTDT = new HashSet<t_CDR_CTDT>();
        }
    
        public int MaKHDT { get; set; }
        public int MaCTDT { get; set; }
        public int MaKhoiKT { get; set; }
        public int MaHP { get; set; }
        public string TenHP { get; set; }
        public string MonTQ { get; set; }
        public string MonHT { get; set; }
        public string MonSH { get; set; }
        public string Hocky { get; set; }
        public string Hinhthuc { get; set; }
        public Nullable<int> SoTC { get; set; }
        public int GioLT { get; set; }
        public int GioTH { get; set; }
        public int GioDA { get; set; }
        public int GioTT { get; set; }
        public string Phanloai { get; set; }
        public string Trinhdo { get; set; }
        public string NgonnguGD { get; set; }
        public string MuctieuHP { get; set; }
        public string Mota { get; set; }
        public string PPGD { get; set; }
        public string PPHT { get; set; }
        public string NhiemvuSV { get; set; }
        public string Thangdiem { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCN { get; set; }
        public string TrangthaiDC { get; set; }
        public string NoidungCN { get; set; }
        public string PhuongtienGD { get; set; }
        public string PhuongtienThi { get; set; }
        public Nullable<System.DateTime> NgayHT { get; set; }
        public string GhichuDG { get; set; }
    
        public virtual sc_Hocphan sc_Hocphan { get; set; }
        public virtual sc_Khoikienthuc sc_Khoikienthuc { get; set; }
        public virtual t_CTDaotao t_CTDaotao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tc_CDR_HP> tc_CDR_HP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tc_DecuongGV> tc_DecuongGV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tc_NoidungHP> tc_NoidungHP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tc_TailieuHP> tc_TailieuHP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sc_LoaiPH> sc_LoaiPH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_CDR_CTDT> t_CDR_CTDT { get; set; }
    }
}
