//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tc_NoidungHP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tc_NoidungHP()
        {
            this.tc_CDR_HP = new HashSet<tc_CDR_HP>();
        }
    
        public int MaND { get; set; }
        public int MaKHDT { get; set; }
        public string Phanloai { get; set; }
        public string Noidung { get; set; }
        public string Hinhthuc { get; set; }
        public string Ghichu { get; set; }
        public string TenHT { get; set; }
    
        public virtual tc_KHDaotao tc_KHDaotao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tc_CDR_HP> tc_CDR_HP { get; set; }
    }
}
