//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tp_ChitietHP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tp_ChitietHP()
        {
            this.tp_TacvuHP = new HashSet<tp_TacvuHP>();
        }
    
        public int MaCTHP { get; set; }
        public Nullable<int> MaKHDT { get; set; }
        public string Tuan { get; set; }
        public string Buoi { get; set; }
    
        public virtual tp_KHDaotao tp_KHDaotao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_TacvuHP> tp_TacvuHP { get; set; }
    }
}
