//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tp_CDR_HP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tp_CDR_HP()
        {
            this.tp_MatranCDR = new HashSet<tp_MatranCDR>();
            this.tp_CDR_HP1 = new HashSet<tp_CDR_HP>();
            this.tp_NoidungHP = new HashSet<tp_NoidungHP>();
            this.tp_DanhgiaHP = new HashSet<tp_DanhgiaHP>();
        }
    
        public int MaCELO { get; set; }
        public int MaKHDT { get; set; }
        public Nullable<int> MaQH { get; set; }
        public string MaHT { get; set; }
        public string Mota { get; set; }
        public string Phanloai { get; set; }
        public string CongCuDanhGia { get; set; }
        public string ThoiDiemDanhGia { get; set; }
    
        public virtual tp_KHDaotao tp_KHDaotao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_MatranCDR> tp_MatranCDR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_CDR_HP> tp_CDR_HP1 { get; set; }
        public virtual tp_CDR_HP tp_CDR_HP2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_NoidungHP> tp_NoidungHP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_DanhgiaHP> tp_DanhgiaHP { get; set; }
    }
}
