//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tp_DecuongGV
    {
        public int MaQL { get; set; }
        public int MaKHDT { get; set; }
        public string NguoiCN { get; set; }
        public string NguoiPC { get; set; }
        public Nullable<System.DateTime> NgayPC { get; set; }
        public string LopHP { get; set; }
        public Nullable<int> GioGD { get; set; }
        public string Trangthai { get; set; }
        public string Ghichu { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual tp_KHDaotao tp_KHDaotao { get; set; }
    }
}
