//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tp_DanhgiaHP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tp_DanhgiaHP()
        {
            this.tp_TieuchiDG = new HashSet<tp_TieuchiDG>();
            this.tp_Lop_TacvuHP = new HashSet<tp_Lop_TacvuHP>();
            this.tp_CDR_HP = new HashSet<tp_CDR_HP>();
            this.tp_TacvuHP = new HashSet<tp_TacvuHP>();
        }
    
        public int MaDG { get; set; }
        public Nullable<int> MaKHDT { get; set; }
        public string Thanhphan { get; set; }
        public string Noidung { get; set; }
        public Nullable<int> Trongso { get; set; }
        public string Ghichu { get; set; }
    
        public virtual tp_KHDaotao tp_KHDaotao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_TieuchiDG> tp_TieuchiDG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_Lop_TacvuHP> tp_Lop_TacvuHP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_CDR_HP> tp_CDR_HP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_TacvuHP> tp_TacvuHP { get; set; }
    }
}
