//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tp_KHDaotao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tp_KHDaotao()
        {
            this.tp_CDR_HP = new HashSet<tp_CDR_HP>();
            this.tp_ChitietHP = new HashSet<tp_ChitietHP>();
            this.tp_DanhgiaHP = new HashSet<tp_DanhgiaHP>();
            this.tp_DecuongGV = new HashSet<tp_DecuongGV>();
            this.tp_LopHP = new HashSet<tp_LopHP>();
            this.tp_NoidungHP = new HashSet<tp_NoidungHP>();
            this.tp_TailieuHP = new HashSet<tp_TailieuHP>();
            this.sc_LoaiPH = new HashSet<sc_LoaiPH>();
        }
    
        public int MaKHDT { get; set; }
        public int MaCTDT { get; set; }
        public Nullable<int> MaHP { get; set; }
        public string TenHP { get; set; }
        public int MaKhoiKT { get; set; }
        public string MonTQ { get; set; }
        public string MonHT { get; set; }
        public string MonSH { get; set; }
        public string Hocky { get; set; }
        public string Namhoc { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public string Hinhthuc { get; set; }
        public int SoTC { get; set; }
        public int GioLT { get; set; }
        public int GioTH { get; set; }
        public int GioDa { get; set; }
        public int GioTT { get; set; }
        public string Phanloai { get; set; }
        public string Trinhdo { get; set; }
        public string NgonnguGD { get; set; }
        public string MuctieuHP { get; set; }
        public string Mota { get; set; }
        public string PPGD { get; set; }
        public string PPHT { get; set; }
        public string NhiemvuSV { get; set; }
        public string Thangdiem { get; set; }
        public string PhuongtienGD { get; set; }
        public string Phuongtienthi { get; set; }
        public System.DateTime Ngaytao { get; set; }
        public Nullable<System.DateTime> NgayCN { get; set; }
        public string NoidungCN { get; set; }
        public string NguoiCN { get; set; }
        public Nullable<System.DateTime> NgayHT { get; set; }
        public Nullable<int> SolopDuKien { get; set; }
        public Nullable<int> SolancapnhatDC { get; set; }
        public string TrangthaiKH { get; set; }
        public string TrangthaiDC { get; set; }
        public string GhichuDG { get; set; }
    
        public virtual t_CTDaotao t_CTDaotao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_CDR_HP> tp_CDR_HP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_ChitietHP> tp_ChitietHP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_DanhgiaHP> tp_DanhgiaHP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_DecuongGV> tp_DecuongGV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_LopHP> tp_LopHP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_NoidungHP> tp_NoidungHP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_TailieuHP> tp_TailieuHP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sc_LoaiPH> sc_LoaiPH { get; set; }
    }
}
