//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tp_Lop_ChitietHP
    {
        public int MaLopCT { get; set; }
        public Nullable<int> MaLop { get; set; }
        public string Tuan { get; set; }
        public string Buoi { get; set; }
        public Nullable<System.DateTime> Ngayhoc { get; set; }
        public Nullable<System.TimeSpan> GioBD { get; set; }
        public Nullable<System.TimeSpan> GioKT { get; set; }
    
        public virtual tp_LopHP tp_LopHP { get; set; }
    }
}
