//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tp_LopHP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tp_LopHP()
        {
            this.tp_Lop_ChitietHP = new HashSet<tp_Lop_ChitietHP>();
            this.tp_LopSV = new HashSet<tp_LopSV>();
            this.tp_TKB = new HashSet<tp_TKB>();
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public int Malop { get; set; }
        public Nullable<int> MaKHDT { get; set; }
        public string Tenlop { get; set; }
        public string Ghichu { get; set; }
        public string DSSVPath { get; set; }
    
        public virtual tp_KHDaotao tp_KHDaotao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_Lop_ChitietHP> tp_Lop_ChitietHP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_LopSV> tp_LopSV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_TKB> tp_TKB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
