//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tp_Lop_TacvuHP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tp_Lop_TacvuHP()
        {
            this.tp_DanhgiaHP = new HashSet<tp_DanhgiaHP>();
        }
    
        public int MaLopTV { get; set; }
        public int MaLopCT { get; set; }
        public int MaND { get; set; }
        public string MaGV { get; set; }
        public string Mota { get; set; }
        public string Phanloai { get; set; }
        public int STT { get; set; }
        public int Douutien { get; set; }
        public int Sogio { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual tp_NoidungHP tp_NoidungHP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_DanhgiaHP> tp_DanhgiaHP { get; set; }
    }
}
