//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tp_LopSV
    {
        public int MaSV { get; set; }
        public string MaQL { get; set; }
        public Nullable<int> MaLop { get; set; }
        public Nullable<int> KhoiLop { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Gioitinh { get; set; }
        public string LopHC { get; set; }
    
        public virtual tp_LopHP tp_LopHP { get; set; }
    }
}
