//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tp_MatranCDR
    {
        public int MaELO { get; set; }
        public int MaCELO { get; set; }
        public string Mucdo { get; set; }
    
        public virtual t_CDR_CTDT t_CDR_CTDT { get; set; }
        public virtual tp_CDR_HP tp_CDR_HP { get; set; }
    }
}
