//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tp_TacvuHP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tp_TacvuHP()
        {
            this.tp_DanhgiaHP = new HashSet<tp_DanhgiaHP>();
        }
    
        public int MaTV { get; set; }
        public Nullable<int> MaCTHP { get; set; }
        public Nullable<int> MaND { get; set; }
        public string Mota { get; set; }
        public string Phanloai { get; set; }
        public Nullable<int> STT { get; set; }
        public Nullable<int> Douutien { get; set; }
        public Nullable<int> Sogio { get; set; }
        public Nullable<bool> HDTL { get; set; }
        public string Ghichu { get; set; }
    
        public virtual tp_ChitietHP tp_ChitietHP { get; set; }
        public virtual tp_NoidungHP tp_NoidungHP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_DanhgiaHP> tp_DanhgiaHP { get; set; }
    }
}
