//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tp_TKB
    {
        public int MaTKB { get; set; }
        public int Malop { get; set; }
        public string Buoi { get; set; }
        public int Thu { get; set; }
        public string GioBD { get; set; }
        public string GioKT { get; set; }
        public string PhongHoc { get; set; }
    
        public virtual tp_LopHP tp_LopHP { get; set; }
    }
}
