//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tp_TieuchiDG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tp_TieuchiDG()
        {
            this.tp_TieuchiDG1 = new HashSet<tp_TieuchiDG>();
        }
    
        public int MaTC { get; set; }
        public Nullable<int> MaDG { get; set; }
        public Nullable<int> MaQH { get; set; }
        public string Mota { get; set; }
        public Nullable<int> Trongso { get; set; }
        public string Mucdo { get; set; }
    
        public virtual tp_DanhgiaHP tp_DanhgiaHP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tp_TieuchiDG> tp_TieuchiDG1 { get; set; }
        public virtual tp_TieuchiDG tp_TieuchiDG2 { get; set; }
    }
}
